READ_DATA:
  MIN_CELLS_PER_GENE: 3
  MIN_FEATURES_PER_CELL: 200
  SCALE_FACTOR: 10000
  NORMALIZATION_METHOD: "LogNormalize"
  SELECTION_METHOD: "vst"
  NFEATURES: 2000
PCA:
  N_PCS: 50
CLUSTERING:
  RESOLUTION: 0.4
  ALGORITHM: 3
UMAP:
  N_NEIGHBORS: 30
  MIN_DIST: 0.3
MARKERS:
  LOGFC_THRESHOLD: 0.25
  MIN_PCT: 0.25
  TEST: "wilcox"
SEED: 123
DIM_REPRESENTATION: 
  REDUCTION_METHOD:
    - "tsne" 
    - "umap" 
  LEGEND:
    - "long_name"
    - "group"
    - "orig.ident"
HEATMAP:
  N_MARKERS: 5
GSEA:
  MIN_GENES: 10
  PVALUE: 0.05
  FDR: 0.1
  P_ADJ_METHOD: "BH"
DE:
  FDR: 0.05
  FC: 0.4
